# Copyright (c) 2024 Boston Dynamics AI Institute LLC. All rights reserved.

from operator import sub

from bosdyn.api import robot_state_pb2
from spatialmath import UnitQuaternion

import numpy as np

def get_base_linear_velocity(state: robot_state_pb2.RobotStateStreamResponse):
    """calculate linear velocity of spots base in the base frame from data
    available in spots state update.  note spot gives velocity in odom frame
    so we need to rotate it to current estimated pose of the base

    arguments
    state -- proto msg from spot containing data on the robots state
    """
    msg = state.kinematic_state.velocity_of_body_in_odom.linear

    odom_r_base_msg = state.kinematic_state.odom_tform_body.rotation
    scalar = odom_r_base_msg.w
    vector = [odom_r_base_msg.x, odom_r_base_msg.y, odom_r_base_msg.z]
    odom_r_base = UnitQuaternion(scalar, vector)

    velocity_odom = np.array([msg.x, msg.y, msg.z])
    velocity_base = None
    try:
        velocity_base = odom_r_base.inv() * velocity_odom
    except:
        print("Failed to calculate base linear velocity!!!")
        return velocity_odom

    return velocity_base


def get_base_angular_velocity(state: robot_state_pb2.RobotStateStreamResponse):
    """calculate angular velocity of spots base in the base frame from data
    available in spots state update.  note spot gives velocity in odom frame
    so we need to rotate it to current estimated pose of the base

    arguments
    state -- proto msg from spot containing data on the robots state
    """
    msg = state.kinematic_state.velocity_of_body_in_odom.angular

    odom_r_base_msg = state.kinematic_state.odom_tform_body.rotation
    scalar = odom_r_base_msg.w
    vector = [odom_r_base_msg.x, odom_r_base_msg.y, odom_r_base_msg.z]
    odom_r_base = UnitQuaternion(scalar, vector)

    angular_velocity_odom = np.array([msg.x, msg.y, msg.z])
    try:
        angular_velocity_base = odom_r_base.inv() * angular_velocity_odom
    except:
        print("Failed to calculate base angular velocity!!!")
        return angular_velocity_odom

    return angular_velocity_base


def get_projected_gravity(state: robot_state_pb2.RobotStateStreamResponse):
    """calculate direction of gravity in spots base frame
        the assumption here is that the odom frame Z axis is opposite gravity
        this is the case if spots body is parallel to the floor when turned on

    arguments
    state -- proto msg from spot containing data on the robots state
    """
    odom_r_base_msg = state.kinematic_state.odom_tform_body.rotation

    scalar = odom_r_base_msg.w
    vector = [odom_r_base_msg.x, odom_r_base_msg.y, odom_r_base_msg.z]
    odom_r_base = UnitQuaternion(scalar, vector)

    gravity_odom = np.array([0, 0, -1])
    try:
        gravity_base = odom_r_base.inv() * gravity_odom
    except:
        print("Failed to calculate projected gravity!!!")
        return gravity_odom

    return gravity_base


def get_joint_positions(
    state: robot_state_pb2.RobotStateStreamResponse, default_joints: list[float]
):
    """Get joint position from spots state update a reformat for orbit by
    reordering to match orbits expectation and shifting so 0 position is the
    same as was used in training

    arguments
    state -- proto msg from spot containing data on the robots state
    config -- dataclass with values loaded from orbits training data
    """
    # I trained with the correct order
    # spot_to_orbit = find_ordering(ORDERED_JOINT_NAMES_SPOT, ORDERED_JOINT_NAMES_ISAAC)
    # pos = reorder(state.joint_states.position, spot_to_orbit)
    pos = list(map(sub, state.joint_states.position, default_joints))
    return pos


def get_joint_velocity(state: robot_state_pb2.RobotStateStreamResponse):
    """get joint velocity from spots state update a reformat for orbit by
    reordering to match orbits expectation

    arguments
    state -- proto msg from spot containing data on the robots state
    """
    # I trained with the correct order
    # spot_to_orbit = find_ordering(ORDERED_JOINT_NAMES_SPOT, ORDERED_JOINT_NAMES_ISAAC)
    # vel = reorder(state.joint_states.velocity, spot_to_orbit)
    return state.joint_states.velocity


def generate_joint_commands(state: robot_state_pb2.RobotStateStreamResponse):
    """
    The joint commands are generated by concatenating the arm joint sub goal,
    leg joint sub goal, and torso roll pitch height goal.

    value = torch.cat(
            [
                self.arm_joint_sub_goal,
                self.leg_joint_sub_goal,
                self.torso_roll_pitch_height_goal,
            ],
            dim=1,
        )

    Right now it is hardcoded for the fixed arm position with no torso inclination
    """
    return [
        0.0000,
        -3.1415,
        3.1415,
        1.5655,
        0.0000,
        0.0000,
        0.0000,
        0.0000,
        0.0000,
        0.0000,
        0.0000,
        0.0000,
        0.0000,
        0.0000,
        0.0000,
        0.0000,
        0.0000,
        0.0000,
        0.0000,
        0.0000,
        0.0000,
        0.0000,
    ]


def get_join_load(state: robot_state_pb2.RobotStateStreamResponse):
    """get joint load from spots state update a reformat for orbit by
    reordering to match orbits expectation

    arguments
    state -- proto msg from spot containing data on the robots state
    """
    # I trained with the correct order
    # spot_to_orbit = find_ordering(ORDERED_JOINT_NAMES_SPOT, ORDERED_JOINT_NAMES_ISAAC)
    # load = reorder(state.joint_states.load, spot_to_orbit)
    return state.joint_states.load


def get_response_timestamp(state: robot_state_pb2.RobotStateStreamResponse):
    """get timestamp from spots state update"""
    return state.header.response_timestamp


# Not working
# def get_joint_acceleration(state: robot_state_pb2.RobotStateStreamResponse):
#     """get joint acceleration from spots state update a reformat for orbit by
#     reordering to match orbits expectation

#     arguments
#     state -- proto msg from spot containing data on the robots state
#     """
#     spot_to_orbit = find_ordering(ORDERED_JOINT_NAMES_SPOT, ORDERED_JOINT_NAMES_ISAAC)
#     acc = reorder(state.joint_states.acceleration, spot_to_orbit)
#     return acc


# Not working
# def get_request_timestamp(state: robot_state_pb2.RobotStateStreamResponse):
#     """get timestamp from spots state update"""
#     return state.header.request_timestamp
